---
- name: Install nginx and index
  hosts: localhost
  become: true
  become_method: su
  
  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present
      
  - name: copy index
    copy:
      src: index.html
      dest: /var/www/html/index.html
      mode: '0644'
